import { Product } from './types/product.model';

export const products: Product[] = [
  {
    id: 1,
    name: 'Laptop X1',
    price: 1200,
    description: 'Powerful laptop with high performance',
    rating: 4.5,
    image: 'laptop_x1.jpg',
    category: 'Laptop',
    brand: 'TechCo',
  },
  {
    id: 2,
    name: 'Desktop Pro',
    price: 1500,
    description: 'Desktop computer for professional use',
    rating: 4.2,
    image: 'desktop_pro.jpg',
    category: 'Desktop',
    brand: 'TechMaster',
  },
  {
    id: 3,
    name: 'Tablet Slim',
    price: 500,
    description: 'Slim and lightweight tablet for on-the-go use',
    rating: 4.0,
    image: 'tablet_slim.jpg',
    category: 'Tablet',
    brand: 'MobileTech',
  },
  {
    id: 4,
    name: 'Keyboard Deluxe',
    price: 50,
    description: 'High-quality mechanical keyboard with RGB lighting',
    rating: 4.8,
    image: 'keyboard_deluxe.jpg',
    category: 'Accessories',
    brand: 'GamerGear',
  },
  {
    id: 5,
    name: 'Graphics Card Turbo',
    price: 300,
    description: 'Turbocharged graphics card for gaming enthusiasts',
    rating: 4.6,
    image: 'graphics_card_turbo.jpg',
    category: 'Hardware',
    brand: 'TechSpeed',
  },
  {
    id: 6,
    name: 'Antivirus Pro',
    price: 30,
    description: 'Professional-grade antivirus software for security',
    rating: 4.7,
    image: 'antivirus_pro.jpg',
    category: 'Software',
    brand: 'SafeGuard',
  },
  {
    id: 7,
    name: 'Gaming Laptop Ultra',
    price: 1800,
    description: 'High-end gaming laptop with ultra graphics',
    rating: 4.9,
    image: 'gaming_laptop_ultra.jpg',
    category: 'Laptop',
    brand: 'GamerTech',
  },
  {
    id: 8,
    name: 'All-in-One Desktop',
    price: 1200,
    description: 'Sleek all-in-one desktop for home and office use',
    rating: 4.3,
    image: 'all_in_one_desktop.jpg',
    category: 'Desktop',
    brand: 'TechSolutions',
  },
  {
    id: 9,
    name: 'Convertible Tablet Pro',
    price: 800,
    description: 'Convertible tablet with pro features for versatility',
    rating: 4.5,
    image: 'convertible_tablet_pro.jpg',
    category: 'Tablet',
    brand: 'FlexTech',
  },
  {
    id: 10,
    name: 'Wireless Mouse Elite',
    price: 40,
    description: 'Precision wireless mouse with ergonomic design',
    rating: 4.7,
    image: 'wireless_mouse_elite.jpg',
    category: 'Accessories',
    brand: 'TechEssentials',
  },
  {
    id: 11,
    name: 'RAM HyperX Fury',
    price: 80,
    description: 'High-performance RAM for speedy multitasking',
    rating: 4.6,
    image: 'ram_hyperx_fury.jpg',
    category: 'Hardware',
    brand: 'HyperX',
  },
  {
    id: 12,
    name: 'Video Editing Software Pro',
    price: 100,
    description: 'Professional video editing software for content creators',
    rating: 4.8,
    image: 'video_editing_software_pro.jpg',
    category: 'Software',
    brand: 'EditMaster',
  },
  {
    id: 13,
    name: 'Ultrabook Slim',
    price: 1300,
    description: 'Slim and lightweight ultrabook for business professionals',
    rating: 4.4,
    image: 'ultrabook_slim.jpg',
    category: 'Laptop',
    brand: 'BusinessTech',
  },
  {
    id: 14,
    name: 'Mini PC Compact',
    price: 600,
    description: 'Compact mini PC for space-saving computing',
    rating: 4.1,
    image: 'mini_pc_compact.jpg',
    category: 'Desktop',
    brand: 'MicroSystems',
  },
  {
    id: 15,
    name: 'Android Tablet Plus',
    price: 300,
    description: 'Feature-rich Android tablet with high-resolution display',
    rating: 4.2,
    image: 'android_tablet_plus.jpg',
    category: 'Tablet',
    brand: 'TechPad',
  },
  {
    id: 16,
    name: 'Mechanical Keyboard Pro',
    price: 80,
    description: 'Pro-grade mechanical keyboard with customizable switches',
    rating: 4.9,
    image: 'mechanical_keyboard_pro.jpg',
    category: 'Accessories',
    brand: 'ProKey',
  },
  {
    id: 17,
    name: 'SSD TurboBoost',
    price: 120,
    description: 'High-speed SSD for turbocharged storage performance',
    rating: 4.7,
    image: 'ssd_turbo_boost.jpg',
    category: 'Hardware',
    brand: 'SpeedTech',
  },
  {
    id: 18,
    name: 'Audio Editing Software Studio',
    price: 120,
    description: 'Studio-quality audio editing software for musicians',
    rating: 4.6,
    image: 'audio_editing_software_studio.jpg',
    category: 'Software',
    brand: 'AudioMaster',
  },
];
