import { Product } from './types/product.model';

export const products: Product[] = [
  {
    id: 1,
    name: 'Laptop X1',
    price: 1200,
    description: 'Powerful laptop with high performance',
    rating: 4.5,
    image: '../assets/images/laptop.jpeg',
    category: 'Laptop',
    brand: 'TechCo',
    soldNumber: 10,
  },
  {
    id: 2,
    name: 'Desktop Pro',
    price: 1500,
    description: 'Desktop computer for professional use',
    rating: 4.2,
    image: '../assets/images/desktop.jpeg',
    category: 'Desktop',
    brand: 'TechMaster',
    soldNumber: 15,
  },
  {
    id: 3,
    name: 'Tablet Slim',
    price: 500,
    description: 'Slim and lightweight tablet for on-the-go use',
    rating: 4.0,
    image: '../assets/images/tablet.jpeg',
    category: 'Tablet',
    brand: 'MobileTech',
    soldNumber: 23,
  },
  {
    id: 4,
    name: 'Keyboard Deluxe',
    price: 50,
    description: 'High-quality mechanical keyboard with RGB lighting',
    rating: 4.8,
    image: '../assets/images/acc-keyboard.jpeg',
    category: 'Accessories',
    brand: 'GamerGear',
    soldNumber: 2,
  },
  {
    id: 5,
    name: 'Graphics Card Turbo',
    price: 300,
    description: 'Turbocharged graphics card for gaming enthusiasts',
    rating: 4.6,
    image: '../assets/images/hardware-gpu.jpeg',
    category: 'Hardware',
    brand: 'TechSpeed',
    soldNumber: 9,
  },
  {
    id: 6,
    name: 'Antivirus Pro',
    price: 30,
    description: 'Professional-grade antivirus software for security',
    rating: 4.7,
    image: '../assets/images/software3.jpeg',
    category: 'Software',
    brand: 'SafeGuard',
    soldNumber: 8,
  },
  {
    id: 7,
    name: 'Gaming Laptop Ultra',
    price: 1800,
    description: 'High-end gaming laptop with ultra graphics',
    rating: 4.9,
    image: '../assets/images/laptop2.jpeg',
    category: 'Laptop',
    brand: 'GamerTech',
    soldNumber: 16,
  },
  {
    id: 8,
    name: 'All-in-One Desktop',
    price: 1200,
    description: 'Sleek all-in-one desktop for home and office use',
    rating: 4.3,
    image: '../assets/images/desktop-aio.jpeg',
    category: 'Desktop',
    brand: 'TechSolutions',
    soldNumber: 87,
  },
  {
    id: 9,
    name: 'Convertible Tablet Pro',
    price: 800,
    description: 'Convertible tablet with pro features for versatility',
    rating: 4.5,
    image: '../assets/images/tablet2.jpeg',
    category: 'Tablet',
    brand: 'FlexTech',
    soldNumber: 35,
  },
  {
    id: 10,
    name: 'Wireless Mouse Elite',
    price: 40,
    description: 'Precision wireless mouse with ergonomic design',
    rating: 4.7,
    image: '../assets/images/mouse.jpeg',
    category: 'Accessories',
    brand: 'TechEssentials',
    soldNumber: 8,
  },
  {
    id: 11,
    name: 'RAM HyperX Fury',
    price: 80,
    description: 'High-performance RAM for speedy multitasking',
    rating: 4.6,
    image: '../assets/images/hardware-ram.jpeg',
    category: 'Hardware',
    brand: 'HyperX',
    soldNumber: 19,
  },
  {
    id: 12,
    name: 'Video Editing Software Pro',
    price: 100,
    description: 'Professional video editing software for content creators',
    rating: 4.8,
    image: '../assets/images/software.jpeg',
    category: 'Software',
    brand: 'EditMaster',
    soldNumber: 7,
  },
  {
    id: 13,
    name: 'Ultrabook Slim',
    price: 1300,
    description: 'Slim and lightweight ultrabook for business professionals',
    rating: 4.4,
    image: '../assets/images/laptop3.jpeg',
    category: 'Laptop',
    brand: 'BusinessTech',
    soldNumber: 19,
  },
  {
    id: 14,
    name: 'Mini PC Compact',
    price: 600,
    description: 'Compact mini PC for space-saving computing',
    rating: 4.1,
    image: '../assets/images/desktop-mini.jpeg',
    category: 'Desktop',
    brand: 'MicroSystems',
    soldNumber: 56,
  },
  {
    id: 15,
    name: 'Android Tablet Plus',
    price: 300,
    description: 'Feature-rich Android tablet with high-resolution display',
    rating: 4.2,
    image: '../assets/images/tablet3.jpeg',
    category: 'Tablet',
    brand: 'TechPad',
    soldNumber: 17,
  },
  {
    id: 16,
    name: 'Mechanical Keyboard Pro',
    price: 80,
    description: 'Pro-grade mechanical keyboard with customizable switches',
    rating: 4.9,
    image: '../assets/images/acc-keyboard2.jpeg',
    category: 'Accessories',
    brand: 'ProKey',
    soldNumber: 4,
  },
  {
    id: 17,
    name: 'SSD TurboBoost',
    price: 120,
    description: 'High-speed SSD for turbocharged storage performance',
    rating: 4.7,
    image: '../assets/images/hardware-ssd.png',
    category: 'Hardware',
    brand: 'SpeedTech',
    soldNumber: 9,
  },
  {
    id: 18,
    name: 'Audio Editing Software Studio',
    price: 120,
    description: 'Studio-quality audio editing software for musicians',
    rating: 4.6,
    image: '../assets/images/software2.jpeg',
    category: 'Software',
    brand: 'AudioMaster',
    soldNumber: 4,
  },
];
